# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          tbt.io
paginate:       5
url:            "https://tbt.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Tobias Berg
  url:          http://tbt.io

# Gems
plugins:
  - jekyll-paginate
